# Generated by Django 5.1.1 on 2024-10-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0002_instructorcourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorcourse",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructorcourses",
                to="instructors.instructor",
            ),
        ),
    ]
