# Generated by Django 5.1.1 on 2024-10-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_studentsubscription_amount_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsubscriptionpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Future", "Future"),
                ],
                max_length=255,
            ),
        ),
    ]
