# Generated by Django 5.1.1 on 2024-10-03 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0002_remove_coursecontent_course_module_coursemoduletopic_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecontent",
            name="course_topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.coursemoduletopic",
            ),
        ),
    ]
