# Generated by Django 5.1.1 on 2024-10-03 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_coursesession_cohort"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                ("assignment_link", models.URLField(null=True)),
                ("due_date", models.DateField()),
                ("total_score", models.IntegerField(default=5)),
                ("active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
