# Generated by Django 5.1.1 on 2024-10-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Student", "Student"),
                    ("Instructor", "Instructor"),
                    ("Freelancer", "Freelancer"),
                ],
                max_length=50,
            ),
        ),
    ]
