# Generated by Django 5.1.1 on 2024-10-03 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("students", "0005_remove_attendance_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="cohort",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.cohort",
            ),
        ),
    ]
