# Generated by Django 5.1.1 on 2024-10-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_assigmentsubmission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assigmentsubmission",
            old_name="assigment",
            new_name="assignment",
        ),
    ]
